### ISSUE TITLE
create common functionality to work with CB cluster

### ISSUE THREAD

**Issue by andreibaranouski** [couchbaselabs/sync-gateway-tests#11]
- [ ] execute any ssh command on remote vms
- [ ] start/stop node
- [ ] wait_for any CB task completed( rebalance, warmup)
- [ ] read CB/nodes statuses

....add more

**Comment by sethrosetter** [comment]
@andreibaranouski start / stop should be doable with ansible. By start / stop, do you mean the machine or sync_gateway or server process?
