### ISSUE TITLE
Tests getting ip from conf/hosts.ini instead of temp_ansible_hosts

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/sync-gateway-tests#58]
Here's my temp_ansible_hosts file:

```
[root@87ff5502835a distributed_index_tests]# cat temp_ansible_hosts
cb1 ansible_ssh_host=ec2-54-162-126-196.compute-1.amazonaws.com
sg1 ansible_ssh_host=ec2-23-22-62-250.compute-1.amazonaws.com
sg2 ansible_ssh_host=ec2-54-211-175-86.compute-1.amazonaws.com

[couchbase_servers]
cb1

[sync_gateways]
sg1
sg2
```

(I generated by writing a /tmp/hosts.ini file, then ran the script to convert to ansible format)

My conf/hosts.ini is the default checked into github.

```
[root@87ff5502835a distributed_index_tests]# cat conf/hosts.ini
[vms]
vm1=172.23.105.164
vm2=172.23.105.165
vm3=172.23.122.250
vm4=172.23.122.251
vm5=172.23.122.252
vm6=172.23.122.253

[couchbase_servers]
cb1=vm1
cb2=vm2

[sync_gateways]
sg1=vm3
sg2=vm4
sg3=vm5
sg4=vm6
```

When I run the tests via:

```
python -m pytest --capture=no tests/test_single_user_multiple_channels.py
```

It's trying to contact the vm 172.23.122.250, which is in conf/hosts.ini but _not_ temp_ansible_hosts.

[Full test output](https://gist.github.com/tleyden/ecb14a2de339afb694c6)

**Comment by tleyden** [comment]
Basically I was under the impression that `temp_ansible_hosts` was the "source of truth" for the ansible inventory, and `conf/hosts.ini` was just used to generate `temp_ansible_hosts`.

**Comment by sethrosetter** [comment]
@tleyden I need to revise that. I'm working on a branch right now and will make improvements to that. As a workaround, just overwrite the local conf/host.ini with yours and that should work.
