### ISSUE TITLE
Run integration tests against Sync Gateway 1.2 in distributed index mode

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/sync-gateway-tests#66]
@ashvindersingh -- can you try it with [this config](https://gist.github.com/tleyden/5c1b7b23d5f22d40ec38)

I did a smoke test locally -- [results](https://gist.github.com/tleyden/7dad9c3307e3f996c1e1)

**Comment by tleyden** [comment]
This is the parameter which allows "mixed mode":

https://gist.github.com/tleyden/5c1b7b23d5f22d40ec38#file-gistfile1-txt-L6

**Comment by zgramana** [comment]
@sethrosetter is going to pick this up opportunistically.

**Comment by sethrosetter** [comment]
Using config

crossed out lines currently target custom config and have not been run in distributed index mode

```
{
    "log": ["CRUD", "REST+", "CHANGES"],
    "skip_runmode_validation" : true,
    "cluster_config": {
        "server":"http://localhost:8091",
        "data_dir":".",
        "bucket":"db"
    },
    "databases": {
        "db": {
            "feed_type":"DCPSHARD",
            "server": "http://localhost:8091",
            "bucket":"db",
            "sync": `
function(doc){
    channel(doc.channels);
}`,
            "users": {
                "GUEST": {"disabled": false, "admin_channels": ["*"] }
            },
            "channel_index":{
                "server":"http://localhost:8091",
                "bucket":"db-index",
                "writer":true
            }
        }
    }
}
```

Tests to run in tests/. 

Against sync_gateway eb6fd2159ae5ffba1b40c76261540768f2a13fbb
- [x] cbl-database.js
- [x] cbl-document.js
- [x] cbl-large-data.js
- [x] cbl-large-revisions.js (https://github.com/couchbase/sync_gateway/issues/1523)
- [x] cbl-large-revisions-compact.js
- [ ] ~~cbl-large-revisions-compact-revs-limit.js (uses different config)~~
- [x] cbl-large-revisions-not-continuous.js
- [ ] ~~cbl-large-revisions-rev_cache_size.js (uses different config)~~
- [x] cbl-replication.js
- [x] cbl-replication-attachements.js
- [x] cbl-replication-mismatch.js
- [x] cbl-replication-mismatch-2-gateways.js (https://github.com/couchbase/sync_gateway/issues/1532)
- [x] cbl-replication-mismatch-restart-cb.js
- [x] cbl-replication-mismatch-restart-gateway.js

Against sync_gateway 4be9943340a09d84a355708be921deaa57a8d2d9
- [x] cbl-replication-restart-gateway.js
- [x] cbl-restart.js - 2 failed / 9 passed (https://gist.github.com/sethrosetter/5ea995f193a37f0bd0e8)
- [ ] cbl-revisions.js - test does not run
- [ ] ~~cbl-simple-requests.js - does not exercise distributed index~~
- [ ] ~~cbl-views.js - does not exercise distributed index~~
- [x] cbl-webhook_events_not_posted.js
- [x] replicate-cbl-sg.js
- [x] sg_changes_feed_last_seq.js - 2 failed / 347 passed (https://gist.github.com/sethrosetter/c52bce537e3388554f6d)

**Comment by sethrosetter** [comment]
I completed a pass locally. https://github.com/couchbase/sync_gateway/issues/1532 is closed as invalid and https://github.com/couchbase/sync_gateway/issues/1523 is marked for fix in 1.3

**Comment by sethrosetter** [comment]
@ashvindersingh got these running in Jenkins. Do you mind posting your results?

**Comment by ashvindersingh** [comment]
http://qa.sc.couchbase.com/view/mobile/job/mobile-integration-tests-cbserver-sync-gateway-cblitios-liteserv/13/
