### ISSUE TITLE
revise all jobs on http://qa.hq.northscale.net/view/mobile/

### ISSUE THREAD

**Issue by andreibaranouski** [couchbaselabs/sync-gateway-tests#8]
- [x] cen006-p0-mobile-cblite-android_cb
- [x] cen006-p0-mobile-sync-gateway-tests-android_cb_bucket_shadowing  
- [x] cen006-p0-mobileupgrade-serverupgrade-sg-cbliteios
- [x] cen006-p0-mobileupgrade-sgupgrade-cblite
- [x] cen006-ps-sgw-vset00-00-sgw-service-install
- [x] cen006-ps-sgw-vset00-00-sgw-web-hook
- [x] centos_x64--100_01--mobile_functional_android
- [x] centos_x64--100_01--mobile_functional_android_from_mobile
- [x] centos_x64--100_02--mobile_unit_tests_android
- [x] centos_x64--100_03--mobile_java
- [x] centos_x64--100_04--sync-gateway-tests
- [x] centos_x64--100_04--sync-gateway-tests-cb
- [x] mac_x64--101_01--mobile_functional_mac_android
- [x] mac_x64--102_01--mobile_functional_mac
- [x] 008-ps-sgw-vset00-00-sgw-service-install
- [ ] w008-ps-sgw-vset00-00-sgw-web-hook

**Comment by andreibaranouski** [comment]
I'm blocked by https://issues.couchbase.com/browse/CBIT-3266

**Comment by sethrosetter** [comment]
@andreibaranouski. Is this done / can be closed?

**Comment by andreibaranouski** [comment]
new jobs from sc jenkins
centos-mobile-sgw-service-install
centos-syncgateway-functional-tests-distributed-index
mobile-functional-tests-android-cb
mobile-sgw-web-hook
mobile_upstream_project
sync-gateway-mobile-functional-tests-android-cb
sync-gateway-mobile-functional-tests-android-cb-bucket_shadowing
